### ISSUE TITLE
ImportError: cannot import name 'escape' from 'jinja2'

### ISSUE THREAD

**Issue by Semnodime** [zk4/livehttp#3]
```
Traceback (most recent call last):
  File "/home/user/.local/bin/livehttp", line 5, in <module>
    from livehttp import entry_point
  File "/home/user/.local/lib/python3.8/site-packages/livehttp/__init__.py", line 1, in <module>
    from .livehttp import (entry_point,
  File "/home/user/.local/lib/python3.8/site-packages/livehttp/livehttp.py", line 5, in <module>
    from flask import Flask, json, send_from_directory, render_template,Response
  File "/home/user/.local/lib/python3.8/site-packages/flask/__init__.py", line 14, in <module>
    from jinja2 import escape
ImportError: cannot import name 'escape' from 'jinja2' (/usr/local/lib/python3.8/dist-packages/jinja2/__init__.py)
```

**Comment by zk4** [comment]
fixed.
